[package]
name = "crush-json"
version = "0.1.0"
authors = ["Masayuki Takeda <mtakeda.enigsol@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"
bincode = "1.3.1"
zstd = { version = "0.5", features = [ "zstdmt" ] }
structopt = "0.3"
num_cpus = "1.0"
